# Generated by Django 4.2.5 on 2023-10-11 13:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='phone',
            field=models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Số điện thoại phải gồm 10 chữ số.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='state',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
