# Generated by Django 4.2.3 on 2023-10-25 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_order_customer_alter_shipping_customer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
