# Generated by Django 4.2.3 on 2023-10-03 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diendan',
            name='ngaytao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diendan',
            name='mota',
            field=models.CharField(max_length=1000),
        ),
    ]
