# Generated by Django 4.2.5 on 2023-10-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_diendan_ngaytao_alter_diendan_mota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diendan',
            name='mota',
            field=models.CharField(max_length=1000000),
        ),
    ]
